# Generated by Django 5.1 on 2024-11-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_imagemproduto_produto_imgproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoriaProduto',
            new_name='catProduto',
        ),
    ]
